import { Option } from '../../src/app/ui/components/menu/menu.component';

/**
 * UNESCO world-region grouping, used by the OER pilot news widget.
 *
 * Source: IRCAI-SDGobservatory/data country_codes/UNESCO-world-regions-sdg.csv
 * (the last column, "UNESCO Regions"). The country-name lookup is built by joining
 * that file's ISO-3166 codes with both the CSV's own country names and this app's
 * COUNTRIES naming, so it resolves the country names the news feed returns.
 */
export const UNESCO_REGIONS: Option[] = [
    { label: 'Africa', value: 'Africa' },
    { label: 'Arab States', value: 'Arab States' },
    { label: 'Asia and the Pacific', value: 'Asia and the Pacific' },
    { label: 'Europe and Northern America', value: 'Europe and Northern America' },
    { label: 'Latin America and the Caribbean', value: 'Latin America and the Caribbean' },
];

const UNESCO_REGION_BY_COUNTRY: Record<string, string> = {
    'afghanistan': 'Asia and the Pacific',
    'aland islands': 'Europe and Northern America',
    'albania': 'Europe and Northern America',
    'algeria': 'Arab States',
    'american samoa': 'Asia and the Pacific',
    'andorra': 'Europe and Northern America',
    'angola': 'Africa',
    'anguilla': 'Latin America and the Caribbean',
    'antigua and barbuda': 'Latin America and the Caribbean',
    'argentina': 'Latin America and the Caribbean',
    'armenia': 'Europe and Northern America',
    'aruba': 'Latin America and the Caribbean',
    'australia': 'Asia and the Pacific',
    'austria': 'Europe and Northern America',
    'azerbaijan': 'Asia and the Pacific',
    'bahamas': 'Latin America and the Caribbean',
    'bahrain': 'Arab States',
    'bangladesh': 'Asia and the Pacific',
    'barbados': 'Latin America and the Caribbean',
    'belarus': 'Europe and Northern America',
    'belgium': 'Europe and Northern America',
    'belize': 'Latin America and the Caribbean',
    'benin': 'Africa',
    'bermuda': 'Europe and Northern America',
    'bhutan': 'Asia and the Pacific',
    'bolivia': 'Latin America and the Caribbean',
    'bolivia, plurinational state of': 'Latin America and the Caribbean',
    'bonaire sint eustatius and saba': 'Latin America and the Caribbean',
    'bonaire, sint eustatius and saba': 'Latin America and the Caribbean',
    'bosnia and herzegovina': 'Europe and Northern America',
    'botswana': 'Africa',
    'bouvet island': 'Latin America and the Caribbean',
    'brazil': 'Latin America and the Caribbean',
    'british indian ocean territory': 'Africa',
    'british virgin islands': 'Latin America and the Caribbean',
    'brunei': 'Asia and the Pacific',
    'brunei darussalam': 'Asia and the Pacific',
    'bulgaria': 'Europe and Northern America',
    'burkina faso': 'Africa',
    'burundi': 'Africa',
    'cabo verde': 'Africa',
    'cambodia': 'Asia and the Pacific',
    'cameroon': 'Africa',
    'canada': 'Europe and Northern America',
    'cape verde': 'Africa',
    'cayman islands': 'Latin America and the Caribbean',
    'central african republic': 'Africa',
    'chad': 'Africa',
    'chile': 'Latin America and the Caribbean',
    'china': 'Asia and the Pacific',
    'christmas island': 'Asia and the Pacific',
    'cocos (keeling) islands': 'Asia and the Pacific',
    'cocos islands': 'Asia and the Pacific',
    'colombia': 'Latin America and the Caribbean',
    'comoros': 'Africa',
    'congo': 'Africa',
    'congo, democratic republic of the': 'Africa',
    'cook islands': 'Asia and the Pacific',
    'costa rica': 'Latin America and the Caribbean',
    'cote d\'ivoire': 'Africa',
    'croatia': 'Europe and Northern America',
    'cuba': 'Latin America and the Caribbean',
    'curacao': 'Latin America and the Caribbean',
    'curaçao': 'Latin America and the Caribbean',
    'cyprus': 'Europe and Northern America',
    'czechia': 'Europe and Northern America',
    'côte d"ivoire': 'Africa',
    'democratic republic of congo': 'Africa',
    'denmark': 'Europe and Northern America',
    'djibouti': 'Arab States',
    'dominica': 'Latin America and the Caribbean',
    'dominican republic': 'Latin America and the Caribbean',
    'east timor': 'Asia and the Pacific',
    'ecuador': 'Latin America and the Caribbean',
    'egypt': 'Arab States',
    'el salvador': 'Latin America and the Caribbean',
    'equatorial guinea': 'Africa',
    'eritrea': 'Africa',
    'estonia': 'Europe and Northern America',
    'eswatini': 'Africa',
    'ethiopia': 'Africa',
    'falkland islands': 'Latin America and the Caribbean',
    'falkland islands (malvinas)': 'Latin America and the Caribbean',
    'faroe islands': 'Europe and Northern America',
    'fiji': 'Asia and the Pacific',
    'finland': 'Europe and Northern America',
    'france': 'Europe and Northern America',
    'french guiana': 'Latin America and the Caribbean',
    'french polynesia': 'Asia and the Pacific',
    'french southern territories': 'Africa',
    'gabon': 'Africa',
    'gambia': 'Africa',
    'georgia': 'Europe and Northern America',
    'germany': 'Europe and Northern America',
    'ghana': 'Africa',
    'gibraltar': 'Europe and Northern America',
    'greece': 'Europe and Northern America',
    'greenland': 'Europe and Northern America',
    'grenada': 'Latin America and the Caribbean',
    'guadeloupe': 'Latin America and the Caribbean',
    'guam': 'Asia and the Pacific',
    'guatemala': 'Latin America and the Caribbean',
    'guernsey': 'Europe and Northern America',
    'guinea': 'Africa',
    'guinea-bissau': 'Africa',
    'guyana': 'Latin America and the Caribbean',
    'haiti': 'Latin America and the Caribbean',
    'heard island and mcdonald islands': 'Asia and the Pacific',
    'holy see': 'Europe and Northern America',
    'honduras': 'Latin America and the Caribbean',
    'hong kong': 'Asia and the Pacific',
    'hungary': 'Europe and Northern America',
    'iceland': 'Europe and Northern America',
    'india': 'Asia and the Pacific',
    'indonesia': 'Asia and the Pacific',
    'iran': 'Asia and the Pacific',
    'iran, islamic republic of': 'Asia and the Pacific',
    'iraq': 'Arab States',
    'ireland': 'Europe and Northern America',
    'isle of man': 'Europe and Northern America',
    'israel': 'Arab States',
    'italy': 'Europe and Northern America',
    'jamaica': 'Latin America and the Caribbean',
    'japan': 'Asia and the Pacific',
    'jersey': 'Europe and Northern America',
    'jordan': 'Arab States',
    'kazakhstan': 'Asia and the Pacific',
    'kenya': 'Africa',
    'kiribati': 'Asia and the Pacific',
    'korea, democratic people"s republic of': 'Asia and the Pacific',
    'korea, republic of': 'Asia and the Pacific',
    'kuwait': 'Arab States',
    'kyrgyzstan': 'Asia and the Pacific',
    'lao people"s democratic republic': 'Asia and the Pacific',
    'laos': 'Asia and the Pacific',
    'latvia': 'Europe and Northern America',
    'lebanon': 'Arab States',
    'lesotho': 'Africa',
    'liberia': 'Africa',
    'libya': 'Arab States',
    'liechtenstein': 'Europe and Northern America',
    'lithuania': 'Europe and Northern America',
    'luxembourg': 'Europe and Northern America',
    'macao': 'Asia and the Pacific',
    'madagascar': 'Africa',
    'malawi': 'Africa',
    'malaysia': 'Asia and the Pacific',
    'maldives': 'Asia and the Pacific',
    'mali': 'Africa',
    'malta': 'Europe and Northern America',
    'marshall islands': 'Asia and the Pacific',
    'martinique': 'Latin America and the Caribbean',
    'mauritania': 'Arab States',
    'mauritius': 'Africa',
    'mayotte': 'Africa',
    'mexico': 'Latin America and the Caribbean',
    'micronesia (country)': 'Asia and the Pacific',
    'micronesia, federated states of': 'Asia and the Pacific',
    'moldova': 'Europe and Northern America',
    'moldova, republic of': 'Europe and Northern America',
    'monaco': 'Europe and Northern America',
    'mongolia': 'Asia and the Pacific',
    'montenegro': 'Europe and Northern America',
    'montserrat': 'Latin America and the Caribbean',
    'morocco': 'Arab States',
    'mozambique': 'Africa',
    'myanmar': 'Asia and the Pacific',
    'namibia': 'Africa',
    'nauru': 'Asia and the Pacific',
    'nepal': 'Asia and the Pacific',
    'netherlands': 'Europe and Northern America',
    'netherlands, kingdom of the': 'Europe and Northern America',
    'new caledonia': 'Asia and the Pacific',
    'new zealand': 'Asia and the Pacific',
    'nicaragua': 'Latin America and the Caribbean',
    'niger': 'Africa',
    'nigeria': 'Africa',
    'niue': 'Asia and the Pacific',
    'norfolk island': 'Asia and the Pacific',
    'north korea': 'Asia and the Pacific',
    'north macedonia': 'Europe and Northern America',
    'northern mariana islands': 'Asia and the Pacific',
    'norway': 'Europe and Northern America',
    'oman': 'Arab States',
    'pakistan': 'Asia and the Pacific',
    'palau': 'Asia and the Pacific',
    'palestine': 'Arab States',
    'palestine, state of': 'Arab States',
    'panama': 'Latin America and the Caribbean',
    'papua new guinea': 'Asia and the Pacific',
    'paraguay': 'Latin America and the Caribbean',
    'peru': 'Latin America and the Caribbean',
    'philippines': 'Asia and the Pacific',
    'pitcairn': 'Asia and the Pacific',
    'poland': 'Europe and Northern America',
    'portugal': 'Europe and Northern America',
    'puerto rico': 'Latin America and the Caribbean',
    'qatar': 'Arab States',
    'reunion': 'Africa',
    'romania': 'Europe and Northern America',
    'russia': 'Europe and Northern America',
    'russian federation': 'Europe and Northern America',
    'rwanda': 'Africa',
    'réunion': 'Africa',
    'saint barthelemy': 'Latin America and the Caribbean',
    'saint barthélemy': 'Latin America and the Caribbean',
    'saint helena': 'Africa',
    'saint helena, ascension and tristan da cunha': 'Africa',
    'saint kitts and nevis': 'Latin America and the Caribbean',
    'saint lucia': 'Latin America and the Caribbean',
    'saint martin (french part)': 'Latin America and the Caribbean',
    'saint pierre and miquelon': 'Europe and Northern America',
    'saint vincent and the grenadines': 'Latin America and the Caribbean',
    'samoa': 'Asia and the Pacific',
    'san marino': 'Europe and Northern America',
    'sao tome and principe': 'Africa',
    'saudi arabia': 'Arab States',
    'senegal': 'Africa',
    'serbia': 'Europe and Northern America',
    'seychelles': 'Africa',
    'sierra leone': 'Africa',
    'singapore': 'Asia and the Pacific',
    'sint maarten (dutch part)': 'Latin America and the Caribbean',
    'slovakia': 'Europe and Northern America',
    'slovenia': 'Europe and Northern America',
    'solomon islands': 'Asia and the Pacific',
    'somalia': 'Africa',
    'south africa': 'Africa',
    'south georgia and the south sandwich islands': 'Latin America and the Caribbean',
    'south korea': 'Asia and the Pacific',
    'south sudan': 'Africa',
    'spain': 'Europe and Northern America',
    'sri lanka': 'Asia and the Pacific',
    'sudan': 'Arab States',
    'suriname': 'Latin America and the Caribbean',
    'svalbard and jan mayen': 'Europe and Northern America',
    'sweden': 'Europe and Northern America',
    'switzerland': 'Europe and Northern America',
    'syria': 'Arab States',
    'syrian arab republic': 'Arab States',
    'tajikistan': 'Asia and the Pacific',
    'tanzania': 'Africa',
    'tanzania, united republic of': 'Africa',
    'thailand': 'Asia and the Pacific',
    'timor-leste': 'Asia and the Pacific',
    'togo': 'Africa',
    'tokelau': 'Asia and the Pacific',
    'tonga': 'Asia and the Pacific',
    'trinidad and tobago': 'Latin America and the Caribbean',
    'tunisia': 'Arab States',
    'turkey': 'Asia and the Pacific',
    'turkmenistan': 'Asia and the Pacific',
    'turks and caicos islands': 'Latin America and the Caribbean',
    'tuvalu': 'Asia and the Pacific',
    'türkiye': 'Asia and the Pacific',
    'uganda': 'Africa',
    'ukraine': 'Europe and Northern America',
    'united arab emirates': 'Arab States',
    'united kingdom': 'Europe and Northern America',
    'united kingdom of great britain and northern ireland': 'Europe and Northern America',
    'united states': 'Europe and Northern America',
    'united states minor outlying islands': 'Asia and the Pacific',
    'united states of america': 'Europe and Northern America',
    'united states virgin islands': 'Latin America and the Caribbean',
    'uruguay': 'Latin America and the Caribbean',
    'uzbekistan': 'Asia and the Pacific',
    'vanuatu': 'Asia and the Pacific',
    'vatican': 'Europe and Northern America',
    'venezuela': 'Latin America and the Caribbean',
    'venezuela, bolivarian republic of': 'Latin America and the Caribbean',
    'viet nam': 'Asia and the Pacific',
    'vietnam': 'Asia and the Pacific',
    'virgin islands (british)': 'Latin America and the Caribbean',
    'virgin islands (u.s.)': 'Latin America and the Caribbean',
    'wallis and futuna': 'Asia and the Pacific',
    'western sahara': 'Arab States',
    'yemen': 'Arab States',
    'zambia': 'Africa',
    'zimbabwe': 'Africa',
    'åland islands': 'Europe and Northern America',
};

export function getUnescoRegion(countryName: string | null | undefined): string | undefined {
    if (!countryName) {
        return undefined;
    }

    return UNESCO_REGION_BY_COUNTRY[countryName.trim().toLowerCase()];
}
